# # SERVICES
services:
# ## web-nginx
    web:
        container_name: web-nginx
        image: nginx:alpine
        volumes:
            #` NGINX-LOGS
            - ./running/var/log/nginx:/var/log/nginx
            #` NGINX-CFG
            #- ./build/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #` base nginx-conf - not necessary
            - ./build/etc/nginx/conf.d:/etc/nginx/conf.d:ro #` vhosts-conf
            #` DOMAINS
            - ./apps/domains:/var/www
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
        restart: unless-stopped
# ## cgi-php-fpm
    php:
        container_name: cgi-php-fpm
        image: php:fpm-alpine
        volumes:
            #` DOMAINS
            - ./apps/domains:/var/www
        depends_on:
            - db
        restart: unless-stopped
# ## db-mariadb
    db:
        container_name: db-mariadb
        image: mariadb:latest
        volumes:
            #` DB-DATA
            #- ./apps/db-mariadb-data:/var/lib/mysql #` For saving
            - ./running/db-mariadb-data:/var/lib/mysql #` For debugging
            # - ./build/initial/sql-scripts/:/docker-entrypoint-initdb.d/ #` Initial SQL-scripts
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake
        environment:
            MYSQL_ROOT_PASSWORD: example_root_password
            MYSQL_DATABASE: example_database
            #MYSQL_USER: example_user
            #MYSQL_PASSWORD: example_password
        #ports:
            #- "3306:3306"
        restart: unless-stopped
# ## dbms-phpmyadmin
    phpmyadmin:
        container_name: dbms-phpmyadmin
        image: phpmyadmin:latest
        #environment:
            #PMA_HOST: mariadb #` Если service называется db, то указывать не нужно
            #PMA_USER: example_user
            #PMA_PASSWORD: example_password
            #MYSQL_ROOT_PASSWORD: example_root_password
        ports:
            - "8001:80"
        restart: unless-stopped
#
# ### Some Notes
# ```docker-compose down; docker-compose up```
# ```bash: sudo docker-compose down && sudo rm -r ./running && sudo cp -r ./build ./running && sudo docker-compose up```
# ```shell: docker-compose down; rm "./running" -Recurse; Copy-Item -Path "./build" -Destination "./running" -Recurse; docker-compose up```
# ```shell: docker-compose down; rm "./running" -Recurse; docker-compose up```
#
# ## certbot
#     certbot:
#         container_name: certbot
#         image: certbot/certbot
#         volumes:
#             #` CERT
#             - ./build/etc/letsencrypt:/etc/letsencrypt
#             #` DOMAINS
#             - ./apps/domains:/var/www
#         command: certonly --webroot --webroot-path=/var/www/example.com --email example@mail.ru --agree-tos --no-eff-email -d example.com
#         depends_on:
#             - web
#         restart: unless-stopped
#